---
- name: Common Setup for all Alef Servers
  hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Ensure system is upto date
    yum:
      name: "*"
      state: latest
    register: updatestatus

  - name: Disable Firewall service
    service:
      name: firewalld
      state: stopped
      enabled: no
  
  - name: restart system to reboot to newest kernel
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    when: updatestatus.changed

  - name: wait for 10 seconds
    pause:
      seconds: 10
    when: updatestatus.changed

  - name: wait for the system to reboot
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60
    when: updatestatus.changed
